services:
  nginx:
    image: mirror.gcr.io/nginx:1.23.4
    container_name: valuator-nginx
    restart: always
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - valuator-1
      - valuator-2
    networks:
      - service-network

  valuator-1:
    container_name: valuator-1
    build:
      context: ./services/valuator
      dockerfile: Dockerfile
    volumes:
      - ./services/valuator/data:/app/data
    networks:
      - service-network

  valuator-2:
    container_name: valuator-2
    build:
      context: ./services/valuator
      dockerfile: Dockerfile
    volumes:
      - ./services/valuator/data:/app/data
    networks:
      - service-network

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass 12345Q
    networks:
      - service-network

networks:
  service-network:

volumes:
  db-data:
  redis_data: