services:
  nginx:
    image: mirror.gcr.io/nginx:1.23.4
    container_name: valuator-nginx
    restart: always
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - valuator-1
      - valuator-2
      - rank-calculator-1
      - rank-calculator-2
    networks:
      - service-network

  valuator-1:
    container_name: valuator-1
    build:
      context: ./services/valuator
      dockerfile: Dockerfile
    volumes:
      - ./services/valuator/data:/app/data
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - service-network

  valuator-2:
    container_name: valuator-2
    build:
      context: ./services/valuator
      dockerfile: Dockerfile
    volumes:
      - ./services/valuator/data:/app/data
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - service-network

  rank-calculator-1:
    container_name: rank-calculator-1
    build: ./services/rank-calculator
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - service-network

  rank-calculator-2:
    container_name: rank-calculator-2
    build: ./services/rank-calculator
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - service-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass 12345Q
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - service-network

  rabbitmq:
    image: mirror.gcr.io/rabbitmq:3.13.7
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - service-network

networks:
  service-network:

volumes:
  db-data:
  redis_data:
  rabbitmq_data: