services:
  valuator:
    container_name: valuator
    build:
      context: ./services/valuator
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./services/valuator/data:/app/data
    networks:
      - service-network

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 12345Q
    networks:
      - service-network

networks:
  service-network:

volumes:
  db-data:
  redis_data: